## COMMANDS DEFINITIONS
battery_percentage_command = "/usr/local/bin/istats | grep 'Current charge' | awk '{print $6}' | tr -dc '0-9\.'"
ac_connected_command = "[[ \"$(system_profiler SPPowerDataType | grep Connected | awk '{print $2}')\" == \"Yes\" ]] && echo \"on\" || echo \"off\""
# ac_current_power = ""
# CPU_percentage_command = "istats | grep 'CPU temp' | awk '{print $3}' | tr -dc '0-9\."
CPU_temperature_command = "/usr/local/bin/istats cpu | awk '{print $3}' | tr -dc '0-9\.'"
SSD_capacity_command = "df -h | grep /dev/disk1s1 | awk '{print $5}' | tr -dc '0-9\.'"
RAM_memory_command = ""
GPU_temperature_command = "/usr/local/bin/istats extra TG0D | awk '{print $6}' | tr -dc '0-9\.'"
battery_temperature_command = "/usr/local/bin/istats battery temp | awk '{print $3}' | tr -dc '0-9\.'"
battery_cycles_command = "/usr/local/bin/istats | grep 'Cycle count' | awk '{print $3}'"
# ram_memory_percentage = ""
# ssd_memory_percentage = ""
